
exports.acitons = {
    CALCULATE_SCORE: "CALCULATE_SCORE",
    START_THE_GAME: "START_THE_GAME",
    GET_RANDOM_BUSH: "GET_RANDOM_BUSH",
    GAME_OVER: "GAME_OVER",
    ON_USER_JOIN: "ON_USER_JOIN",
    ALL_USER_JOINED: "ALL_USER_JOINED",
    ON_ERROR: "ON_ERROR",
    ON_USER_LEAVE: "ON_USER_LEAVE",
}